from datetime import datetime
from flask_sqlalchemy import SQLAlchemy


db = SQLAlchemy()


class BusinessProfile(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255), nullable=False)
    website_url = db.Column(db.String(255))
    audience = db.Column(db.Text)
    offer = db.Column(db.Text)
    brand_voice = db.Column(db.Text)
    main_cta = db.Column(db.String(255))
    traffic_goal = db.Column(db.Text)
    core_topics_json = db.Column(db.Text)
    money_pages_json = db.Column(db.Text)
    primary_keywords_json = db.Column(db.Text)
    competitors_json = db.Column(db.Text)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)


class ProjectCaseStudy(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    business_id = db.Column(db.Integer, db.ForeignKey('business_profile.id'), nullable=False)
    campaign_id = db.Column(db.Integer, db.ForeignKey('campaign.id'))
    project_name = db.Column(db.String(255), nullable=False)
    problem_solved = db.Column(db.Text)
    system_built = db.Column(db.Text)
    tools_used = db.Column(db.Text)
    before_state = db.Column(db.Text)
    after_state = db.Column(db.Text)
    result = db.Column(db.Text)
    target_reader = db.Column(db.String(255))
    notes = db.Column(db.Text)
    real_examples = db.Column(db.Text)
    screenshots_needed = db.Column(db.Text)
    proof_points = db.Column(db.Text)
    lessons_learned = db.Column(db.Text)
    what_we_would_improve = db.Column(db.Text)
    campaign = db.Column(db.String(255))
    created_at = db.Column(db.DateTime, default=datetime.utcnow)


class ContentBrief(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    business_id = db.Column(db.Integer, db.ForeignKey('business_profile.id'), nullable=False)
    case_study_id = db.Column(db.Integer, db.ForeignKey('project_case_study.id'), nullable=True)
    target_keyword = db.Column(db.String(255))
    search_intent = db.Column(db.String(255))
    ai_search_answer_type = db.Column(db.String(100))
    traffic_goal = db.Column(db.Text)
    target_money_page = db.Column(db.String(255))
    post_type = db.Column(db.String(100))
    buyer_stage = db.Column(db.String(50))
    title_options_json = db.Column(db.Text)
    selected_title = db.Column(db.String(255))
    h1 = db.Column(db.String(255))
    outline_json = db.Column(db.Text)
    faqs_json = db.Column(db.Text)
    cta = db.Column(db.String(255))
    internal_link_targets_json = db.Column(db.Text)
    meta_title = db.Column(db.String(255))
    meta_description = db.Column(db.Text)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)


class BlogPost(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    business_id = db.Column(db.Integer, db.ForeignKey('business_profile.id'), nullable=False)
    case_study_id = db.Column(db.Integer, db.ForeignKey('project_case_study.id'), nullable=True)
    content_brief_id = db.Column(db.Integer, db.ForeignKey('content_brief.id'))
    title = db.Column(db.String(255))
    slug = db.Column(db.String(255))
    excerpt = db.Column(db.Text)
    category = db.Column(db.String(255))
    tags_json = db.Column(db.Text)
    body_markdown = db.Column(db.Text)
    edited_body_markdown = db.Column(db.Text)
    seo_title = db.Column(db.String(255))
    meta_description = db.Column(db.Text)
    image_prompt = db.Column(db.Text)
    image_alt_text = db.Column(db.String(255))
    image_quality_json = db.Column(db.Text)
    recommended_image_type = db.Column(db.String(100))
    image_style_notes = db.Column(db.Text)
    image_negative_prompt = db.Column(db.Text)
    image_brief = db.Column(db.Text)
    internal_links_json = db.Column(db.Text)
    seo_publish_checklist_json = db.Column(db.Text)
    target_keyword = db.Column(db.String(255))
    pipeline_status = db.Column(db.String(50), default='draft')
    search_intent = db.Column(db.String(50))
    ai_search_answer_type = db.Column(db.String(100))
    traffic_goal = db.Column(db.Text)
    target_money_page = db.Column(db.String(255))
    post_type = db.Column(db.String(100))
    buyer_stage = db.Column(db.String(50))
    traffic_intent = db.Column(db.String(255))
    business_value_score = db.Column(db.Integer)
    ranking_opportunity_score = db.Column(db.Integer)
    publish_priority = db.Column(db.String(50))
    internal_link_priority = db.Column(db.String(50))
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    ai_answer_block = db.Column(db.Text)
    internal_link_plan_json = db.Column(db.Text)
    cta_plan_json = db.Column(db.Text)
    claim_check_json = db.Column(db.Text)
    publish_checklist_json = db.Column(db.Text)
    repurposing_json = db.Column(db.Text)
    refresh_plan_json = db.Column(db.Text)
    lead_readiness_score = db.Column(db.Integer)
    tracking_plan_json = db.Column(db.Text)
    publish_readiness_json = db.Column(db.Text)
    money_page_alignment_json = db.Column(db.Text)
    lead_path_json = db.Column(db.Text)
    lead_magnet_json = db.Column(db.Text)
    real_assets_needed_json = db.Column(db.Text)
    secondary_cta = db.Column(db.String(255))
    primary_cta = db.Column(db.String(255))
    conversion_goal = db.Column(db.String(100))
    wordpress_post_id = db.Column(db.Integer)
    wordpress_post_url = db.Column(db.String(500))
    wordpress_edit_url = db.Column(db.String(500))
    wordpress_status = db.Column(db.String(50))
    sent_to_wordpress_at = db.Column(db.DateTime)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


class NicheOpportunity(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    business_id = db.Column(db.Integer, db.ForeignKey('business_profile.id'), nullable=False)
    campaign_id = db.Column(db.Integer, db.ForeignKey('campaign.id'))
    query = db.Column(db.String(255), nullable=False)
    recommended_title = db.Column(db.String(255))
    post_type = db.Column(db.String(100))
    search_intent = db.Column(db.String(50))
    buyer_stage = db.Column(db.String(50))
    target_money_page = db.Column(db.String(255))
    business_value_score = db.Column(db.Integer)
    ranking_opportunity_score = db.Column(db.Integer)
    why_it_can_win = db.Column(db.Text)
    content_angle = db.Column(db.Text)
    cta = db.Column(db.String(255))
    status = db.Column(db.String(50), default='idea')
    created_at = db.Column(db.DateTime, default=datetime.utcnow)


class Campaign(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    business_id = db.Column(db.Integer, db.ForeignKey('business_profile.id'), nullable=False)
    name = db.Column(db.String(255), nullable=False)
    goal = db.Column(db.Text)
    target_money_page = db.Column(db.String(255))
    primary_keyword = db.Column(db.String(255))
    audience = db.Column(db.Text)
    lead_magnet_idea = db.Column(db.String(255))
    primary_cta = db.Column(db.String(255))
    status = db.Column(db.String(50), default='planning')
    created_at = db.Column(db.DateTime, default=datetime.utcnow)


class TopicCluster(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    business_id = db.Column(db.Integer, db.ForeignKey('business_profile.id'), nullable=False)
    money_page = db.Column(db.String(255), nullable=False)
    cluster_name = db.Column(db.String(255))
    pillar_topic = db.Column(db.String(255))
    supporting_posts_json = db.Column(db.Text)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)


class AgentRun(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    business_id = db.Column(db.Integer, db.ForeignKey('business_profile.id'), nullable=False)
    case_study_id = db.Column(db.Integer, db.ForeignKey('project_case_study.id'), nullable=True)
    blog_post_id = db.Column(db.Integer, db.ForeignKey('blog_post.id'))
    agent_name = db.Column(db.String(100), nullable=False)
    input_json = db.Column(db.Text)
    output_json = db.Column(db.Text)
    status = db.Column(db.String(50), default='started')
    error_message = db.Column(db.Text)
    started_at = db.Column(db.DateTime, default=datetime.utcnow)
    finished_at = db.Column(db.DateTime)
